# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: federated.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'federated.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x65\x64\x65rated.proto\x12\tfederated\"!\n\x0f\x44ownloadRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\x05\"A\n\nModelChunk\x12\x0e\n\x06job_id\x18\x01 \x01(\x05\x12\x0f\n\x07node_id\x18\x02 \x01(\x05\x12\x12\n\nchunk_data\x18\x03 \x01(\x0c\"2\n\x0eUploadResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\x98\x01\n\rModelTransfer\x12\x44\n\rDownloadModel\x12\x1a.federated.DownloadRequest\x1a\x15.federated.ModelChunk0\x01\x12\x41\n\x0bUploadModel\x12\x15.federated.ModelChunk\x1a\x19.federated.UploadResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'federated_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOWNLOADREQUEST']._serialized_start=30
  _globals['_DOWNLOADREQUEST']._serialized_end=63
  _globals['_MODELCHUNK']._serialized_start=65
  _globals['_MODELCHUNK']._serialized_end=130
  _globals['_UPLOADRESPONSE']._serialized_start=132
  _globals['_UPLOADRESPONSE']._serialized_end=182
  _globals['_MODELTRANSFER']._serialized_start=185
  _globals['_MODELTRANSFER']._serialized_end=337
# @@protoc_insertion_point(module_scope)
