# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import federated_pb2 as federated__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in federated_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModelTransferStub(object):
    """The Service defines the remote functions the Edge Node can call on the Hub
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DownloadModel = channel.unary_stream(
                '/federated.ModelTransfer/DownloadModel',
                request_serializer=federated__pb2.DownloadRequest.SerializeToString,
                response_deserializer=federated__pb2.ModelChunk.FromString,
                _registered_method=True)
        self.UploadModel = channel.stream_unary(
                '/federated.ModelTransfer/UploadModel',
                request_serializer=federated__pb2.ModelChunk.SerializeToString,
                response_deserializer=federated__pb2.UploadResponse.FromString,
                _registered_method=True)


class ModelTransferServicer(object):
    """The Service defines the remote functions the Edge Node can call on the Hub
    """

    def DownloadModel(self, request, context):
        """1. Download: Edge asks for a job, Hub streams back the model in chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadModel(self, request_iterator, context):
        """2. Upload: Edge streams its local model up in chunks, Hub replies when done
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelTransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DownloadModel': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadModel,
                    request_deserializer=federated__pb2.DownloadRequest.FromString,
                    response_serializer=federated__pb2.ModelChunk.SerializeToString,
            ),
            'UploadModel': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadModel,
                    request_deserializer=federated__pb2.ModelChunk.FromString,
                    response_serializer=federated__pb2.UploadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'federated.ModelTransfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('federated.ModelTransfer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelTransfer(object):
    """The Service defines the remote functions the Edge Node can call on the Hub
    """

    @staticmethod
    def DownloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/federated.ModelTransfer/DownloadModel',
            federated__pb2.DownloadRequest.SerializeToString,
            federated__pb2.ModelChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadModel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/federated.ModelTransfer/UploadModel',
            federated__pb2.ModelChunk.SerializeToString,
            federated__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
